# Database Connection
spring.datasource.url=jdbc:${SQL_HOST}:${SQL_PORT}/${SQL_DATABASE}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# File upload config
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=200MB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=blhblhbinu@gmail.com
spring.mail.password=ltfa dvmx hcta ovii
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Flyway setup
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.application.name=detroit
